// Copyright JNJ,  All Rights Reserved.

#pragma once

#include "CoreMinimal.h"

#include "NativeGameplayTags.h"

namespace Mw_ItemTags
{
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item);
	// Item Type
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Basic);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Equippable);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Consumable);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Type_Craftable);
	
	// Item Rarity
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity_Common);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity_UnCommon);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity_Rare);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity_Epic);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Rarity_Legendary);
	
	// Item Category
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon_OneHandedSword);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon_OneHandedSword_L);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon_OneHandedSword_R);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Equippable_Weapon_DoubleHandedSword);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Consumable);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Craftable);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_None);
	/**
	 * Unset Weapon Spell Food Potion Armor Material
	 */ 
	
	// Item Equipment Slots
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Head);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Hand_LeftAndRight);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Hand_Left);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Hand_Right);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Chest);
	MAGICWORLD_V03_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_EquipmentSlot_Feet);
	
}
