// Copyright JNJ,  All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/**
 * 标签
 * 声明MAGIC WORLD将使用的所有自定义原生标签
 */
namespace Mw_GameplayTags
{
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MwAbilities_Strategy_OnlyGiven);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MwAbilities_Strategy_GiveAndActivate);

#pragma region 	/** Begin： Input **/
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_ToggleInventory);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquip);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LMB);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RMB);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shift);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_Trigger);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_Complete);
	
#pragma endregion	/** End： Input **/

#pragma region 	/** Begin： Ability **/
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Equip);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UnEquip);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ComboX);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ComboXX);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ComboXXX);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ComboXY);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ComboY);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Action_Roll);
#pragma endregion	/** End： Ability **/

#pragma region 	/** Begin： Status **/
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Equip_Weapon_Left);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Equip_Weapon_Right);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Equip_Weapon_Double);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UnEquip_Weapon_Left);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UnEquip_Weapon_Right);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UnEquip_Weapon_Double);
	
	
#pragma endregion	/** End： Status **/
	
#pragma region 	/** Begin： ANS **/
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(AN_Event_Interact);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANS_Window_Combo);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ANS_Window_CantRoll);
	
#pragma endregion	/** End： ANS **/
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionState_Equip);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionState_UnEquip);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionState_Start);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ActionState_Comboing);
	
#pragma region 	/** Begin： AnimInStance **/
	
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_TargetLock);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_ADS);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_WeaponFire);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Reload);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Dash);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_Melee);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Walking);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Jogging);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Running);
#pragma endregion	/** End： AnimInStance **/
	
#pragma region	/** Begin： Message UI tags **/
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HealthCrystal);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HealthPotion);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_ManaPotion);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_StaminaPotion);

#pragma endregion	/** End： Message UI tags  **/	
	
	
#pragma region /** Begin： AttributeSets tags **/
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Vitality);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Concentration);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Endurance);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Strength);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Dexterity);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Intelligence);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Primary_Faith);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Health);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxHealth);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Mana);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxMana);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Stamina);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxStamina);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_Weight);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Vital_MaxWeight);
	
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Combat_Attack);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Combat_Defense);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Combat_MagicAttack);
	MAGICWORLD_V03_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attributes_Combat_MagicDefense);

	
#pragma endregion /** End： AttributeSets tags **/
	
};
